export const ingredients = [
  "tomato",
  "basil",
  "olive oil",
  "garlic",
  "parmesan",
  "mozzarella",
  "oregano",
  "pasta",
  "cumin",
  "turmeric",
  "coriander",
  "garam masala",
  "ginger",
  "chili",
  "lentils",
  "ghee",
  "soy sauce",
  "ginger",
  "garlic",
  "sesame oil",
  "rice vinegar",
  "tofu",
  "bok choy",
  "noodles",
  "corn",
  "beans",
  "chili peppers",
  "cilantro",
  "avocado",
  "lime",
  "tomatillo",
  "tortilla",
  "chickpeas",
  "tahini",
  "sumac",
  "mint",
  "lamb",
  "yogurt",
  "bulgur",
  "beef",
  "cheddar cheese",
  "potatoes",
  "barbecue sauce",
  "cornbread",
  "bacon",
  "lettuce",
  "tomato",
  "butter",
  "cream",
  "thyme",
  "shallots",
  "wine",
  "mushrooms",
  "leeks",
  "herbs de Provence",
  "millet",
  "sorghum",
  "yams",
  "cassava",
  "peanuts",
  "okra",
  "berbere",
  "plantains",
];

export const timeRanges = [
  { label: "Quick (15-30 min)", value: "quick" },
  { label: "Medium (30-60 min)", value: "medium" },
  { label: "Long (>60 min)", value: "long" },
];

export const dummyRecipes = Array.from({ length: 12 }).map((_, i) => ({
  id: i + 1,
  title: `Sample Recipe ${i + 1}`,
  author: "Chef John Doe",
  rating: 4 + (i % 2),
  reviews: 120 + i * 3,
  time: `${30 + i * 5} min`,
  timeRange: ["quick", "medium", "long"][i % 3],
  image: "https://source.unsplash.com/300x200/?chicken,dish",
}));
